name: pamsimas_jadi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0-beta.2
  dio: ^5.4.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
  adaptive_icon_background: "#00000000" # transparan
  adaptive_icon_foreground: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
